### ISSUE TITLE
URL 변경

### ISSUE THREAD

**Issue by sukso96100** [s-owl/skhus-backend#18]
종합정보시스템(forest.skhu.ac.kr) 에서 신뢰 가능한 SSL/TLS 인증서(RapidSSL) 사용함에 따라
http://forest.skhu.ac.kr -> https://forest.skhu.ac.kr 로 URL 변경.

학사행정시스템(sam.skhu.ac.kr) 은 아직 정부가 발급한 **대부분의 웹 브라우저와 클라이언트가 신뢰하지 않는** 인증서를 여전히 사용하므로, 인증서 바뀔 때 까지 보류.

**Comment by tpdns90321** [comment]
OK
