### ISSUE TITLE
간혈적으로 forest에서 로그인 결과가 전송받지 않아 프로세스가 죽는 문제

### ISSUE THREAD

**Issue by tpdns90321** [s-owl/skhus-backend#23]
panic: runtime error: index out of range
github.com/s-owl/skhus-backend/user.loginOnForest.func1.1(0xbcde00, 0xc000093ea0, 0xd9cea0, 0xc0006d1ef0, 0xc0000a5b30, 0x2c, 0xc0002a3bc8, 0xc000036f00, 0xc000201c80, 0x32, ...)
/build/user/login.go:111 +0x397

**Comment by tpdns90321** [comment]
일단은 ecs랑 로드밸런서에서 죽는 거 확인하고 다시 살려내기는 하는데 운 않좋아서 이거 걸리면 또 로그인해야하는 불쌍한 사람을 막기위해서 빨리 해결합시다.

**Comment by sukso96100** [comment]
마스터 브랜치 쪽인가? 테스트 채널은 어떰?

**Comment by tpdns90321** [comment]
마스터 브랜치 쪽에서 일어나고 있어요

**Comment by tpdns90321** [comment]
테스트 쪽은 문제가 없는 것 같아요

**Comment by sukso96100** [comment]
그럼 테스트 좀만 더 손보고 바로 올려야겠다 아직 과목조회등 chromedp 쓰는 일부 api 에 싱글톤 형태 브라우저 적용이 안 되어 있음

**Comment by tpdns90321** [comment]
테스트 쪽에서도 동일하게 발생확률은 있을걸요? 이거 chromedp 이벤트 받아서 처리할 때 빈 타겟을 주는 것 같아요

**Comment by tpdns90321** [comment]
저번 딴 구현체 만들 때 경험했는데 현재 구현채에서도 발생할 줄은 몰랐죠. 그래서 develop 코드에 넣었났는데 다시 넣어야겠네요. 근데 이 문제가 빈 타겟이 오고 다시 이벤트가 들어오나가 문제인 것 같네요. 예외처리에 고민을 해야겠어요.

**Comment by sukso96100** [comment]
ok

**Comment by sukso96100** [comment]
일단 이 부분에서 터지는건가 간혈적으로?
```go
currentURL := targets[0].URL
```
